adds CI job to run Robot integration tests

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -18,14 +18,16 @@ workflows:
   # WORKFLOW 1/1 Build, Test & Analyze FHIR-bridge code
   build_and_test_fhirbridge:
     jobs:
-      - build-and-test-fhirbridge:
+        - build-and-quicktest-fhirbridge:
             context: org-global
-        #   filters:
-        #     branches:
-        #       ignore:
-        #         - master
-        #         - develop
-        #         - release
+            #   filters:
+            #     branches:
+            #       ignore:
+            #         - master
+            #         - develop
+            #         - release
+        - build-and-test-fhirbridge:
+            context: org-global
 
 
 
@@ -44,8 +46,8 @@ jobs:
     #    "Y8888P"     `"Y8888Y"'    88888888P"    "Y88888P"
     
     
-    build-and-test-fhirbridge:
-        description: Build and test FHIR-bridge, analyze code, upload results to sonarcloud.io
+    build-and-quicktest-fhirbridge:
+        description: Build and test FHIR-bridge
         executor: docker-py3-java11-postgres
         steps:
             - checkout
@@ -58,10 +60,36 @@ jobs:
             - build-and-test-fhirbridge
             - cache-in-ehrbase-m2-dependencies
             - cache-in-fhirbridge-m2-dependencies
-            # - collect-fhirbride-unittest-results
+            # - collect-fhirbridge-unittest-results
             - collect-fhirbridge-integrationtest-results
             - save-fhirbridge-test-results
             - save-jacoco-coverage-report
+            # - sonarcloud/scan:
+            #     cache_version: 1
+
+
+    build-and-test-fhirbridge:
+        description: |
+            Build and test FHIR-bridge, analyze code, collect code coverage metrics,
+            upload results to sonarcloud.io
+        executor: docker-py3-java11-postgres
+        steps:
+            - checkout
+            - install-maven
+            - git-clone-ehrbase-repo
+            - cache-out-fhirbridge-m2-dependencies
+            - cache-out-ehrbase-m2-dependencies
+            - build-ehrbase
+            - start-ehrbase-server
+            - build-and-test-fhirbridge
+            - cache-in-ehrbase-m2-dependencies
+            - cache-in-fhirbridge-m2-dependencies
+            # - collect-fhirbridge-unittest-results
+            - collect-fhirbridge-integrationtest-results
+            - save-fhirbridge-test-results
+            - save-jacoco-coverage-report
+            - start-fhirbridge-application
+            - run-robot-integration-tests
             - sonarcloud/scan:
                 cache_version: 1
 
@@ -154,6 +182,57 @@ commands:
                     mvn clean verify -Dmaven.javadoc.skip=true -Dspring.profiles.active=ci
 
 
+    start-fhirbridge-application:
+        steps:
+            - run:
+                name: START FHIRBRIDGE APPLICATION
+                background: true
+                command: |
+                    ls -la
+                    FHIRBRIDGE_VERSION=$(mvn -q -Dexec.executable="echo" \
+                                             -Dexec.args='${project.version}' \
+                                             --non-recursive exec:exec)
+                    echo "FHIRBRIDGE_VERSION: ${FHIRBRIDGE_VERSION}"
+                    java -jar "target/fhir-bridge-${FHIRBRIDGE_VERSION}.jar" > fhirbride_log
+
+            - run:
+                name: WAIT FOR FHIRBRIDE TO BE READY
+                command: |
+                    ls -la
+                    timeout=30
+                    while [ ! -f fhirbride_log ];
+                        do
+                            echo "Waiting for file fhirbride_log ..."
+                            if [ "$timeout" == 0 ]; then
+                                echo "ERROR: timed out while waiting for file fhirbride_log"
+                                exit 1
+                            fi
+                            sleep 1
+                        ((timeout--))
+                    done
+                    while ! (cat fhirbride_log | grep -m 1 "Started FhirBridgeApplication in");
+                        do
+                            echo "waiting for FHIR-Bridge to be ready ...";
+                            if [ "$timeout" == 0 ]; then
+                                echo "WARNING: Did not see a startup message even after waiting 30s"
+                                exit 1
+                            fi
+                            sleep 1;
+                        ((timeout--))
+                    done
+                    echo "REMAINING TIMEOUT: $timeout"
+                    jps
+
+
+    run-robot-integration-tests:
+        steps:
+            - install-robot-dependencies
+            - run:
+                name: RUN ROBOT TESTS
+                command: |
+                    robot -d results -L TRACE -e todo --noncritical not-ready robot/
+
+            
     cache-out-fhirbridge-m2-dependencies:
         steps:
             - run:
@@ -261,6 +340,14 @@ commands:
                     sudo apt -y update
                     [ -f /usr/bin/mvn ] && echo "Maven is already installed." || sudo apt install maven -y
 
+    install-robot-dependencies:
+        description: Install Python requirements
+        steps:
+            - run:
+                name: Install Python requirements
+                command: |
+                    python -c "import site; print(site.getsitepackages())"
+                    pip install -r tests/requirements.txt
 
 
 
